### ISSUE TITLE
反馈bug

### ISSUE THREAD

**Issue by gabor1252** [Chocolate1999/hexo-blog-lionkk#1]
主题下的_config.yml中的设置大部分不起作用

**Comment by Chocolate1999** [comment]
这个是主题原因，目的是为了平滑升级，如果需要修改主题配置内容，请在source/_data/butterfly.yml文件修改即可（不是在主题的_config.yml文件，butterfly.yml会覆盖原主题配置文件）

**Comment by Chocolate1999** [comment]
> 主题下的_config.yml中的设置大部分不起作用

这个是主题原因，目的是为了平滑升级，如果需要修改主题配置内容，请在source/_data/butterfly.yml文件修改即可（不是在主题的_config.yml文件，butterfly.yml会覆盖原主题配置文件）

**Comment by gabor1252** [comment]
抱歉，失了智

**Comment by Chocolate1999** [comment]
> 抱歉，失了智

没事没事，谢谢提出Issues

**Comment by chuchendjs** [comment]
大佬，你的那个日历表下面出现了滚动条，上面也没有显示当前日历
