### ISSUE TITLE
访客地图的修改

### ISSUE THREAD

**Issue by Zhang-Each** [Chocolate1999/hexo-blog-lionkk#21]
在使用过程中发现了一个问题，如果card_map设置为true的时候显示的访客地图始终是原作者的，如果需要修改成自己博客的访客地图，需要先注册申请clustrmaps，并修改Butterfly主题下的`layout/includes/widget/card_map.pug`文件，将最后一行的src修改成自己对应的url

**Comment by Chocolate1999** [comment]
可以，是需要自己注册一个，然后进行配置

**Comment by Chocolate1999** [comment]
@Zhang-Each 

过去在博客搭建教程里面有写哈，具体可以参考：https://yangchaoyi.vip/posts/520520/#%E6%B7%BB%E5%8A%A0%E8%AE%BF%E5%AE%A2%E5%9C%B0%E5%9B%BE
