### ISSUE TITLE
评论区无法正常加载可能是什么原因？

### ISSUE THREAD

**Issue by Zhang-Each** [Chocolate1999/hexo-blog-lionkk#22]
最近尝试在添加评论区功能，在配置文件对应的地方设置好之后，实际部署的博客上评论区一直无法显示，可能是什么原因？valine和disqus都试过了，具体的效果大概这样 [点击此处访问](https://zhang-each.github.io/2022/08/23/cmu-dis-sys4/)

**Comment by Chocolate1999** [comment]
```
comments:
    use: ["Valine","Gitalk"]
```

有这样配置吗，一般情况下评论添加好相关配置信息就可以，也可以看看 https://twikoo.js.org/，比 valine 更好点。

**Comment by Zhang-Each** [comment]
感谢🙏，问题解决了，我在use这里填了Valine，不知道要用这种格式填写
