### ISSUE TITLE
无法修改样式是什么原因？

### ISSUE THREAD

**Issue by KingJacM** [Chocolate1999/hexo-blog-lionkk#37]
我跟着提供的文档做了，clone之后npm install，但是当我自行设置例如放一个`disable_top_img: true` 在root或者theme的config里面没有任何变化，inject css也是一样。

**Comment by Chocolate1999** [comment]
> 我跟着提供的文档做了，clone之后npm install，但是当我自行设置例如放一个`disable_top_img: true` 在root或者theme的config里面没有任何变化，inject css也是一样。

修改 config 配置文件，一般需要重启一下服务，hexo g && hexo s 这样
